# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/puzzlebox_jigsaw_interface_design-plugin_web.ui'
#
# Created: Sun May 10 18:28:34 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
#Form.resize()
		#self.verticalLayoutWidget = QtGui.QWidget(Form)
		self.verticalLayoutWidget = QtGui.QWidget()
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(-5, 0, 389, 80))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayoutToolbar = QtGui.QHBoxLayout()
		self.horizontalLayoutToolbar.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.horizontalLayoutToolbar.setContentsMargins(6, -1, 6, -1)
		self.horizontalLayoutToolbar.setObjectName("horizontalLayoutToolbar")
		self.pushButtonWebBack = QtGui.QPushButton(self.verticalLayoutWidget)
		self.pushButtonWebBack.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("images/jigsaw_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonWebBack.setIcon(icon)
		self.pushButtonWebBack.setObjectName("pushButtonWebBack")
		self.horizontalLayoutToolbar.addWidget(self.pushButtonWebBack)
		self.pushButtonWebForward = QtGui.QPushButton(self.verticalLayoutWidget)
		self.pushButtonWebForward.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("images/jigsaw_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonWebForward.setIcon(icon1)
		self.pushButtonWebForward.setObjectName("pushButtonWebForward")
		self.horizontalLayoutToolbar.addWidget(self.pushButtonWebForward)
		self.lineEditWebLocation = QtGui.QLineEdit(self.verticalLayoutWidget)
		self.lineEditWebLocation.setObjectName("lineEditWebLocation")
		self.horizontalLayoutToolbar.addWidget(self.lineEditWebLocation)
		self.pushButtonWebStop = QtGui.QPushButton(self.verticalLayoutWidget)
		self.pushButtonWebStop.setText("")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("images/jigsaw_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonWebStop.setIcon(icon2)
		self.pushButtonWebStop.setObjectName("pushButtonWebStop")
		self.horizontalLayoutToolbar.addWidget(self.pushButtonWebStop)
		self.pushButtonWebReload = QtGui.QPushButton(self.verticalLayoutWidget)
		self.pushButtonWebReload.setText("")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("images/jigsaw_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonWebReload.setIcon(icon3)
		self.pushButtonWebReload.setObjectName("pushButtonWebReload")
		self.horizontalLayoutToolbar.addWidget(self.pushButtonWebReload)
		self.verticalLayout.addLayout(self.horizontalLayoutToolbar)
		self.webViewWebBrowser = QtWebKit.QWebView(self.verticalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.webViewWebBrowser.sizePolicy().hasHeightForWidth())
		self.webViewWebBrowser.setSizePolicy(sizePolicy)
		self.webViewWebBrowser.setUrl(QtCore.QUrl("http://www.google.com/"))
		self.webViewWebBrowser.setObjectName("webViewWebBrowser")
		self.verticalLayout.addWidget(self.webViewWebBrowser)
		self.horizontalLayoutStatusBar = QtGui.QHBoxLayout()
		self.horizontalLayoutStatusBar.setObjectName("horizontalLayoutStatusBar")
		self.lineEditWebStatus = QtGui.QLineEdit(self.verticalLayoutWidget)
		self.lineEditWebStatus.setEnabled(False)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditWebStatus.sizePolicy().hasHeightForWidth())
		self.lineEditWebStatus.setSizePolicy(sizePolicy)
		self.lineEditWebStatus.setObjectName("lineEditWebStatus")
		self.horizontalLayoutStatusBar.addWidget(self.lineEditWebStatus)
		self.progressBarWebProgress = QtGui.QProgressBar(self.verticalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.progressBarWebProgress.sizePolicy().hasHeightForWidth())
		self.progressBarWebProgress.setSizePolicy(sizePolicy)
		self.progressBarWebProgress.setProperty("value", 0)
		self.progressBarWebProgress.setTextVisible(True)
		self.progressBarWebProgress.setObjectName("progressBarWebProgress")
		self.horizontalLayoutStatusBar.addWidget(self.progressBarWebProgress)
		self.verticalLayout.addLayout(self.horizontalLayoutStatusBar)

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		Form.setWindowTitle(QtGui.QApplication.translate("Form", "Puzzlebox Jigsaw - Plug-in - Web Browser", None, QtGui.QApplication.UnicodeUTF8))
		self.lineEditWebLocation.setText(QtGui.QApplication.translate("Form", "http://www.google.com", None, QtGui.QApplication.UnicodeUTF8))
		self.lineEditWebStatus.setText(QtGui.QApplication.translate("Form", "Status: N/A", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
