# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/puzzlebox_jigsaw_interface_design-plugin_session.ui'
#
# Created: Sun May 10 18:28:33 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
#Form.resize()
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
		Form.setSizePolicy(sizePolicy)
		Form.setFocusPolicy(QtCore.Qt.NoFocus)
		#self.verticalLayoutWidget = QtGui.QWidget(Form)
		self.verticalLayoutWidget = QtGui.QWidget()
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 992, 856))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setSpacing(6)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout_3 = QtGui.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem)
		self.verticalLayoutFeedback = QtGui.QVBoxLayout()
		self.verticalLayoutFeedback.setObjectName("verticalLayoutFeedback")
		self.horizontalLayout = QtGui.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem1)
		self.labelPuzzleboxControlPanel = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelPuzzleboxControlPanel.setText("")
		self.labelPuzzleboxControlPanel.setPixmap(QtGui.QPixmap("images/puzzlebox_logo.png"))
		self.labelPuzzleboxControlPanel.setScaledContents(False)
		self.labelPuzzleboxControlPanel.setAlignment(QtCore.Qt.AlignCenter)
		self.labelPuzzleboxControlPanel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.labelPuzzleboxControlPanel.setObjectName("labelPuzzleboxControlPanel")
		self.horizontalLayout.addWidget(self.labelPuzzleboxControlPanel)
		self.textLabelTitlePuzzleboxJigsaw = QtGui.QLabel(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.textLabelTitlePuzzleboxJigsaw.setFont(font)
		self.textLabelTitlePuzzleboxJigsaw.setTextFormat(QtCore.Qt.AutoText)
		self.textLabelTitlePuzzleboxJigsaw.setWordWrap(False)
		self.textLabelTitlePuzzleboxJigsaw.setOpenExternalLinks(True)
		self.textLabelTitlePuzzleboxJigsaw.setObjectName("textLabelTitlePuzzleboxJigsaw")
		self.horizontalLayout.addWidget(self.textLabelTitlePuzzleboxJigsaw)
		spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem2)
		self.verticalLayoutFeedback.addLayout(self.horizontalLayout)
		spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		self.verticalLayoutFeedback.addItem(spacerItem3)
		self.labelSessionProfile = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionProfile.setObjectName("labelSessionProfile")
		self.verticalLayoutFeedback.addWidget(self.labelSessionProfile)
		self.lineEditSessionProfile = QtGui.QLineEdit(self.verticalLayoutWidget)
		self.lineEditSessionProfile.setAlignment(QtCore.Qt.AlignCenter)
		self.lineEditSessionProfile.setObjectName("lineEditSessionProfile")
		self.verticalLayoutFeedback.addWidget(self.lineEditSessionProfile)
		self.lineSessionData = QtGui.QFrame(self.verticalLayoutWidget)
		self.lineSessionData.setFrameShape(QtGui.QFrame.HLine)
		self.lineSessionData.setFrameShadow(QtGui.QFrame.Sunken)
		self.lineSessionData.setObjectName("lineSessionData")
		self.verticalLayoutFeedback.addWidget(self.lineSessionData)
		self.labelSessionProfileData = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionProfileData.setObjectName("labelSessionProfileData")
		self.verticalLayoutFeedback.addWidget(self.labelSessionProfileData)
		self.formLayoutSessionData = QtGui.QFormLayout()
		self.formLayoutSessionData.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
		self.formLayoutSessionData.setObjectName("formLayoutSessionData")
		self.textLabelSessionTimeTitle = QtGui.QLabel(self.verticalLayoutWidget)
		self.textLabelSessionTimeTitle.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelSessionTimeTitle.setObjectName("textLabelSessionTimeTitle")
		self.formLayoutSessionData.setWidget(0, QtGui.QFormLayout.LabelRole, self.textLabelSessionTimeTitle)
		self.textLabelSessionTime = QtGui.QLabel(self.verticalLayoutWidget)
		self.textLabelSessionTime.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelSessionTime.setObjectName("textLabelSessionTime")
		self.formLayoutSessionData.setWidget(0, QtGui.QFormLayout.FieldRole, self.textLabelSessionTime)
		self.verticalLayoutFeedback.addLayout(self.formLayoutSessionData)
		spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		self.verticalLayoutFeedback.addItem(spacerItem4)
		self.horizontalLayoutSessionButtons = QtGui.QHBoxLayout()
		self.horizontalLayoutSessionButtons.setObjectName("horizontalLayoutSessionButtons")
		self.pushButtonSessionSave = QtGui.QPushButton(self.verticalLayoutWidget)
		self.pushButtonSessionSave.setEnabled(False)
		self.pushButtonSessionSave.setObjectName("pushButtonSessionSave")
		self.horizontalLayoutSessionButtons.addWidget(self.pushButtonSessionSave)
		self.pushButtonSessionExport = QtGui.QPushButton(self.verticalLayoutWidget)
		self.pushButtonSessionExport.setEnabled(False)
		self.pushButtonSessionExport.setObjectName("pushButtonSessionExport")
		self.horizontalLayoutSessionButtons.addWidget(self.pushButtonSessionExport)
		self.pushButtonSessionReset = QtGui.QPushButton(self.verticalLayoutWidget)
		self.pushButtonSessionReset.setEnabled(False)
		self.pushButtonSessionReset.setObjectName("pushButtonSessionReset")
		self.horizontalLayoutSessionButtons.addWidget(self.pushButtonSessionReset)
		self.verticalLayoutFeedback.addLayout(self.horizontalLayoutSessionButtons)
		self.lineSessionPluginNone_2 = QtGui.QFrame(self.verticalLayoutWidget)
		self.lineSessionPluginNone_2.setFrameShape(QtGui.QFrame.HLine)
		self.lineSessionPluginNone_2.setFrameShadow(QtGui.QFrame.Sunken)
		self.lineSessionPluginNone_2.setObjectName("lineSessionPluginNone_2")
		self.verticalLayoutFeedback.addWidget(self.lineSessionPluginNone_2)
		self.formLayoutJSONHostPort = QtGui.QFormLayout()
		self.formLayoutJSONHostPort.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.formLayoutJSONHostPort.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
		self.formLayoutJSONHostPort.setObjectName("formLayoutJSONHostPort")
		self.textLabelJSONHost = QtGui.QLabel(self.verticalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelJSONHost.sizePolicy().hasHeightForWidth())
		self.textLabelJSONHost.setSizePolicy(sizePolicy)
		self.textLabelJSONHost.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelJSONHost.setObjectName("textLabelJSONHost")
		self.formLayoutJSONHostPort.setWidget(0, QtGui.QFormLayout.LabelRole, self.textLabelJSONHost)
		self.lineEditJSONHost = QtGui.QLineEdit(self.verticalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditJSONHost.sizePolicy().hasHeightForWidth())
		self.lineEditJSONHost.setSizePolicy(sizePolicy)
		self.lineEditJSONHost.setAlignment(QtCore.Qt.AlignHCenter)
		self.lineEditJSONHost.setObjectName("lineEditJSONHost")
		self.formLayoutJSONHostPort.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditJSONHost)
		self.textLabelJSONPort = QtGui.QLabel(self.verticalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelJSONPort.sizePolicy().hasHeightForWidth())
		self.textLabelJSONPort.setSizePolicy(sizePolicy)
		self.textLabelJSONPort.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelJSONPort.setWordWrap(False)
		self.textLabelJSONPort.setObjectName("textLabelJSONPort")
		self.formLayoutJSONHostPort.setWidget(1, QtGui.QFormLayout.LabelRole, self.textLabelJSONPort)
		self.lineEditJSONPort = QtGui.QLineEdit(self.verticalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditJSONPort.sizePolicy().hasHeightForWidth())
		self.lineEditJSONPort.setSizePolicy(sizePolicy)
		self.lineEditJSONPort.setAlignment(QtCore.Qt.AlignHCenter)
		self.lineEditJSONPort.setObjectName("lineEditJSONPort")
		self.formLayoutJSONHostPort.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditJSONPort)
		self.verticalLayoutFeedback.addLayout(self.formLayoutJSONHostPort)
		self.horizontalLayoutSessionButtons_2 = QtGui.QHBoxLayout()
		self.horizontalLayoutSessionButtons_2.setObjectName("horizontalLayoutSessionButtons_2")
		spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutSessionButtons_2.addItem(spacerItem5)
		self.pushButtonSessionJSON = QtGui.QPushButton(self.verticalLayoutWidget)
		self.pushButtonSessionJSON.setEnabled(True)
		self.pushButtonSessionJSON.setObjectName("pushButtonSessionJSON")
		self.horizontalLayoutSessionButtons_2.addWidget(self.pushButtonSessionJSON)
		spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutSessionButtons_2.addItem(spacerItem6)
		self.verticalLayoutFeedback.addLayout(self.horizontalLayoutSessionButtons_2)
		spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutFeedback.addItem(spacerItem7)
		self.horizontalLayout_3.addLayout(self.verticalLayoutFeedback)
		spacerItem8 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem8)
		self.lineVertical = QtGui.QFrame(self.verticalLayoutWidget)
		self.lineVertical.setFrameShape(QtGui.QFrame.VLine)
		self.lineVertical.setFrameShadow(QtGui.QFrame.Sunken)
		self.lineVertical.setObjectName("lineVertical")
		self.horizontalLayout_3.addWidget(self.lineVertical)
		spacerItem9 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem9)
		self.verticalLayout_4 = QtGui.QVBoxLayout()
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		self.verticalLayout_4.addItem(spacerItem10)
		self.labelSessionActivePlugins = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionActivePlugins.setObjectName("labelSessionActivePlugins")
		self.verticalLayout_4.addWidget(self.labelSessionActivePlugins)
		self.lineActivePlugins = QtGui.QFrame(self.verticalLayoutWidget)
		self.lineActivePlugins.setFrameShape(QtGui.QFrame.HLine)
		self.lineActivePlugins.setFrameShadow(QtGui.QFrame.Sunken)
		self.lineActivePlugins.setObjectName("lineActivePlugins")
		self.verticalLayout_4.addWidget(self.lineActivePlugins)
		self.labelSessionPluginNone = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionPluginNone.setObjectName("labelSessionPluginNone")
		self.verticalLayout_4.addWidget(self.labelSessionPluginNone)
		self.lineSessionPluginNone = QtGui.QFrame(self.verticalLayoutWidget)
		self.lineSessionPluginNone.setFrameShape(QtGui.QFrame.HLine)
		self.lineSessionPluginNone.setFrameShadow(QtGui.QFrame.Sunken)
		self.lineSessionPluginNone.setObjectName("lineSessionPluginNone")
		self.verticalLayout_4.addWidget(self.lineSessionPluginNone)
		self.labelSessionPluginAPI = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionPluginAPI.setObjectName("labelSessionPluginAPI")
		self.verticalLayout_4.addWidget(self.labelSessionPluginAPI)
		self.horizontalLayout_2 = QtGui.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem11)
		self.checkBoxServiceEnableJSON = QtGui.QCheckBox(self.verticalLayoutWidget)
		self.checkBoxServiceEnableJSON.setChecked(False)
		self.checkBoxServiceEnableJSON.setObjectName("checkBoxServiceEnableJSON")
		self.horizontalLayout_2.addWidget(self.checkBoxServiceEnableJSON)
		spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem12)
		self.verticalLayout_4.addLayout(self.horizontalLayout_2)
		self.lineSessionPluginAPI = QtGui.QFrame(self.verticalLayoutWidget)
		self.lineSessionPluginAPI.setFrameShape(QtGui.QFrame.HLine)
		self.lineSessionPluginAPI.setFrameShadow(QtGui.QFrame.Sunken)
		self.lineSessionPluginAPI.setObjectName("lineSessionPluginAPI")
		self.verticalLayout_4.addWidget(self.lineSessionPluginAPI)
		self.labelSessionPluginEEG = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionPluginEEG.setObjectName("labelSessionPluginEEG")
		self.verticalLayout_4.addWidget(self.labelSessionPluginEEG)
		self.labelSessionPluginEEGStatus = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionPluginEEGStatus.setAlignment(QtCore.Qt.AlignCenter)
		self.labelSessionPluginEEGStatus.setObjectName("labelSessionPluginEEGStatus")
		self.verticalLayout_4.addWidget(self.labelSessionPluginEEGStatus)
		self.formLayoutSessionPluginEEG = QtGui.QFormLayout()
		self.formLayoutSessionPluginEEG.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
		self.formLayoutSessionPluginEEG.setObjectName("formLayoutSessionPluginEEG")
		self.textLabelConnectionTimeTitle = QtGui.QLabel(self.verticalLayoutWidget)
		self.textLabelConnectionTimeTitle.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelConnectionTimeTitle.setObjectName("textLabelConnectionTimeTitle")
		self.formLayoutSessionPluginEEG.setWidget(0, QtGui.QFormLayout.LabelRole, self.textLabelConnectionTimeTitle)
		self.textLabelConnectionTime = QtGui.QLabel(self.verticalLayoutWidget)
		self.textLabelConnectionTime.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelConnectionTime.setObjectName("textLabelConnectionTime")
		self.formLayoutSessionPluginEEG.setWidget(0, QtGui.QFormLayout.FieldRole, self.textLabelConnectionTime)
		self.textLabelPacketsReceivedTitle = QtGui.QLabel(self.verticalLayoutWidget)
		self.textLabelPacketsReceivedTitle.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelPacketsReceivedTitle.setObjectName("textLabelPacketsReceivedTitle")
		self.formLayoutSessionPluginEEG.setWidget(1, QtGui.QFormLayout.LabelRole, self.textLabelPacketsReceivedTitle)
		self.textLabelPacketsReceived = QtGui.QLabel(self.verticalLayoutWidget)
		self.textLabelPacketsReceived.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelPacketsReceived.setObjectName("textLabelPacketsReceived")
		self.formLayoutSessionPluginEEG.setWidget(1, QtGui.QFormLayout.FieldRole, self.textLabelPacketsReceived)
		self.textLabelPacketsDroppedTitle = QtGui.QLabel(self.verticalLayoutWidget)
		self.textLabelPacketsDroppedTitle.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelPacketsDroppedTitle.setObjectName("textLabelPacketsDroppedTitle")
		self.formLayoutSessionPluginEEG.setWidget(2, QtGui.QFormLayout.LabelRole, self.textLabelPacketsDroppedTitle)
		self.textLabelPacketsDropped = QtGui.QLabel(self.verticalLayoutWidget)
		self.textLabelPacketsDropped.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelPacketsDropped.setObjectName("textLabelPacketsDropped")
		self.formLayoutSessionPluginEEG.setWidget(2, QtGui.QFormLayout.FieldRole, self.textLabelPacketsDropped)
		self.verticalLayout_4.addLayout(self.formLayoutSessionPluginEEG)
		self.lineSessionPluginEEG = QtGui.QFrame(self.verticalLayoutWidget)
		self.lineSessionPluginEEG.setFrameShape(QtGui.QFrame.HLine)
		self.lineSessionPluginEEG.setFrameShadow(QtGui.QFrame.Sunken)
		self.lineSessionPluginEEG.setObjectName("lineSessionPluginEEG")
		self.verticalLayout_4.addWidget(self.lineSessionPluginEEG)
		self.labelSessionPluginWeb = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionPluginWeb.setObjectName("labelSessionPluginWeb")
		self.verticalLayout_4.addWidget(self.labelSessionPluginWeb)
		self.labelSessionPluginWebStatus = QtGui.QLabel(self.verticalLayoutWidget)
		self.labelSessionPluginWebStatus.setAlignment(QtCore.Qt.AlignCenter)
		self.labelSessionPluginWebStatus.setObjectName("labelSessionPluginWebStatus")
		self.verticalLayout_4.addWidget(self.labelSessionPluginWebStatus)
		spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayout_4.addItem(spacerItem13)
		self.horizontalLayout_3.addLayout(self.verticalLayout_4)
		spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem14)
		self.verticalLayout.addLayout(self.horizontalLayout_3)
		self.labelSessionGraphic = QtGui.QLabel(self.verticalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.labelSessionGraphic.sizePolicy().hasHeightForWidth())
		self.labelSessionGraphic.setSizePolicy(sizePolicy)
		self.labelSessionGraphic.setText("")
		self.labelSessionGraphic.setPixmap(QtGui.QPixmap("images/puzzlebox_jigsaw.png"))
		self.labelSessionGraphic.setScaledContents(True)
		self.labelSessionGraphic.setObjectName("labelSessionGraphic")
		self.verticalLayout.addWidget(self.labelSessionGraphic)
		spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayout.addItem(spacerItem15)

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelTitlePuzzleboxJigsaw.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://jigsaw.puzzlebox.info\"><span style=\" font-size:11pt; font-weight:600; text-decoration: none; color:#000000;\">Puzzlebox<br />Jigsaw</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionProfile.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Session Profile</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.lineEditSessionProfile.setText(QtGui.QApplication.translate("Form", "Untitled Session", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionProfileData.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Session Data</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelSessionTimeTitle.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Session Time</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelSessionTime.setText(QtGui.QApplication.translate("Form", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonSessionSave.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonSessionExport.setText(QtGui.QApplication.translate("Form", "Export", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonSessionReset.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelJSONHost.setText(QtGui.QApplication.translate("Form", "JSON API Host", None, QtGui.QApplication.UnicodeUTF8))
		self.lineEditJSONHost.setText(QtGui.QApplication.translate("Form", "N/A", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelJSONPort.setText(QtGui.QApplication.translate("Form", "<html><head/><body><p align=\"center\">JSON API Port</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.lineEditJSONPort.setText(QtGui.QApplication.translate("Form", "N/A", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonSessionJSON.setText(QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionActivePlugins.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Active Plug-ins</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionPluginNone.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">None</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionPluginAPI.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">API</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.checkBoxServiceEnableJSON.setText(QtGui.QApplication.translate("Form", "Permit Remote Access", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionPluginEEG.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">EEG</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionPluginEEGStatus.setText(QtGui.QApplication.translate("Form", "Status: Disconnected", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelConnectionTimeTitle.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Connection Time</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelConnectionTime.setText(QtGui.QApplication.translate("Form", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelPacketsReceivedTitle.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Packets Received</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelPacketsReceived.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelPacketsDroppedTitle.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Packets Dropped</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelPacketsDropped.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionPluginWeb.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Web</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelSessionPluginWebStatus.setText(QtGui.QApplication.translate("Form", "Status: Available", None, QtGui.QApplication.UnicodeUTF8))

