# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/puzzlebox_jigsaw_interface_design-plugin_eeg.ui'
#
# Created: Sun May 10 18:28:33 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
#Form.resize()
		Form.setAutoFillBackground(False)
		self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
		self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 975, 776))
		self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
		self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout_7 = QtGui.QHBoxLayout()
		self.horizontalLayout_7.setContentsMargins(4, 4, 4, 4)
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_7.addItem(spacerItem)
		self.verticalLayoutEEGSource = QtGui.QVBoxLayout()
		self.verticalLayoutEEGSource.setSpacing(6)
		self.verticalLayoutEEGSource.setObjectName("verticalLayoutEEGSource")
		self.labelEEGHeadsetModel = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.labelEEGHeadsetModel.setAlignment(QtCore.Qt.AlignCenter)
		self.labelEEGHeadsetModel.setObjectName("labelEEGHeadsetModel")
		self.verticalLayoutEEGSource.addWidget(self.labelEEGHeadsetModel)
		self.comboBoxEEGHeadsetModel = QtGui.QComboBox(self.verticalLayoutWidget_2)
		self.comboBoxEEGHeadsetModel.setEnabled(True)
		self.comboBoxEEGHeadsetModel.setFocusPolicy(QtCore.Qt.NoFocus)
		self.comboBoxEEGHeadsetModel.setObjectName("comboBoxEEGHeadsetModel")
		self.comboBoxEEGHeadsetModel.addItem("")
		self.comboBoxEEGHeadsetModel.addItem("")
		self.comboBoxEEGHeadsetModel.addItem("")
		self.comboBoxEEGHeadsetModel.addItem("")
		self.comboBoxEEGHeadsetModel.addItem("")
		self.verticalLayoutEEGSource.addWidget(self.comboBoxEEGHeadsetModel)
		self.line_3 = QtGui.QFrame(self.verticalLayoutWidget_2)
		self.line_3.setFrameShape(QtGui.QFrame.HLine)
		self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
		self.line_3.setObjectName("line_3")
		self.verticalLayoutEEGSource.addWidget(self.line_3)
		self.labelEEGServerSource = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.labelEEGServerSource.setAlignment(QtCore.Qt.AlignCenter)
		self.labelEEGServerSource.setObjectName("labelEEGServerSource")
		self.verticalLayoutEEGSource.addWidget(self.labelEEGServerSource)
		self.comboBoxEEGSource = QtGui.QComboBox(self.verticalLayoutWidget_2)
		self.comboBoxEEGSource.setEnabled(True)
		self.comboBoxEEGSource.setObjectName("comboBoxEEGSource")
		self.comboBoxEEGSource.addItem("")
		self.comboBoxEEGSource.addItem("")
		self.comboBoxEEGSource.addItem("")
		self.comboBoxEEGSource.addItem("")
		self.comboBoxEEGSource.addItem("")
		self.comboBoxEEGSource.addItem("")
		self.comboBoxEEGSource.addItem("")
		self.verticalLayoutEEGSource.addWidget(self.comboBoxEEGSource)
		self.comboBoxDeviceSelect = QtGui.QComboBox(self.verticalLayoutWidget_2)
		self.comboBoxDeviceSelect.setObjectName("comboBoxDeviceSelect")
		self.comboBoxDeviceSelect.addItem("")
		self.verticalLayoutEEGSource.addWidget(self.comboBoxDeviceSelect)
		self.pushButtonControlSearch = QtGui.QPushButton(self.verticalLayoutWidget_2)
		self.pushButtonControlSearch.setObjectName("pushButtonControlSearch")
		self.verticalLayoutEEGSource.addWidget(self.pushButtonControlSearch)
		self.checkBoxControlEmulateThinkGear = QtGui.QCheckBox(self.verticalLayoutWidget_2)
		self.checkBoxControlEmulateThinkGear.setChecked(True)
		self.checkBoxControlEmulateThinkGear.setObjectName("checkBoxControlEmulateThinkGear")
		self.verticalLayoutEEGSource.addWidget(self.checkBoxControlEmulateThinkGear)
		self.lineControlSourceServer = QtGui.QFrame(self.verticalLayoutWidget_2)
		self.lineControlSourceServer.setFrameShape(QtGui.QFrame.HLine)
		self.lineControlSourceServer.setFrameShadow(QtGui.QFrame.Sunken)
		self.lineControlSourceServer.setObjectName("lineControlSourceServer")
		self.verticalLayoutEEGSource.addWidget(self.lineControlSourceServer)
		self.checkBoxControlEnableServer = QtGui.QCheckBox(self.verticalLayoutWidget_2)
		self.checkBoxControlEnableServer.setChecked(True)
		self.checkBoxControlEnableServer.setObjectName("checkBoxControlEnableServer")
		self.verticalLayoutEEGSource.addWidget(self.checkBoxControlEnableServer)
		self.formLayoutControlHostPort = QtGui.QFormLayout()
		self.formLayoutControlHostPort.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.formLayoutControlHostPort.setObjectName("formLayoutControlHostPort")
		self.textLabelSynapseHost = QtGui.QLabel(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelSynapseHost.sizePolicy().hasHeightForWidth())
		self.textLabelSynapseHost.setSizePolicy(sizePolicy)
		self.textLabelSynapseHost.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelSynapseHost.setObjectName("textLabelSynapseHost")
		self.formLayoutControlHostPort.setWidget(0, QtGui.QFormLayout.LabelRole, self.textLabelSynapseHost)
		self.lineEditSynapseHost = QtGui.QLineEdit(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditSynapseHost.sizePolicy().hasHeightForWidth())
		self.lineEditSynapseHost.setSizePolicy(sizePolicy)
		self.lineEditSynapseHost.setAlignment(QtCore.Qt.AlignHCenter)
		self.lineEditSynapseHost.setObjectName("lineEditSynapseHost")
		self.formLayoutControlHostPort.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditSynapseHost)
		self.textLabelSynapsePort = QtGui.QLabel(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelSynapsePort.sizePolicy().hasHeightForWidth())
		self.textLabelSynapsePort.setSizePolicy(sizePolicy)
		self.textLabelSynapsePort.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelSynapsePort.setWordWrap(False)
		self.textLabelSynapsePort.setObjectName("textLabelSynapsePort")
		self.formLayoutControlHostPort.setWidget(1, QtGui.QFormLayout.LabelRole, self.textLabelSynapsePort)
		self.lineEditSynapsePort = QtGui.QLineEdit(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditSynapsePort.sizePolicy().hasHeightForWidth())
		self.lineEditSynapsePort.setSizePolicy(sizePolicy)
		self.lineEditSynapsePort.setAlignment(QtCore.Qt.AlignHCenter)
		self.lineEditSynapsePort.setObjectName("lineEditSynapsePort")
		self.formLayoutControlHostPort.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditSynapsePort)
		self.verticalLayoutEEGSource.addLayout(self.formLayoutControlHostPort)
		self.horizontalLayout_3 = QtGui.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.pushButtonSynapseServer = QtGui.QPushButton(self.verticalLayoutWidget_2)
		self.pushButtonSynapseServer.setMinimumSize(QtCore.QSize(0, 64))
		self.pushButtonSynapseServer.setObjectName("pushButtonSynapseServer")
		self.horizontalLayout_3.addWidget(self.pushButtonSynapseServer)
		self.verticalLayoutEEGSource.addLayout(self.horizontalLayout_3)
		spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutEEGSource.addItem(spacerItem1)
		self.horizontalLayout_7.addLayout(self.verticalLayoutEEGSource)
		self.verticalLayoutEEGPlot = QtGui.QVBoxLayout()
		self.verticalLayoutEEGPlot.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.verticalLayoutEEGPlot.setObjectName("verticalLayoutEEGPlot")
		self.horizontalLayoutChartTop = QtGui.QHBoxLayout()
		self.horizontalLayoutChartTop.setObjectName("horizontalLayoutChartTop")
		spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutChartTop.addItem(spacerItem2)
		self.labelChartTop = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.labelChartTop.setObjectName("labelChartTop")
		self.horizontalLayoutChartTop.addWidget(self.labelChartTop)
		spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutChartTop.addItem(spacerItem3)
		self.verticalLayoutEEGPlot.addLayout(self.horizontalLayoutChartTop)
		self.widgetPlotRawEEG = QtGui.QWidget(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widgetPlotRawEEG.sizePolicy().hasHeightForWidth())
		self.widgetPlotRawEEG.setSizePolicy(sizePolicy)
		self.widgetPlotRawEEG.setMinimumSize(QtCore.QSize(520, 160))
		self.widgetPlotRawEEG.setObjectName("widgetPlotRawEEG")
		self.labelMockupRawEEG = QtGui.QLabel(self.widgetPlotRawEEG)
		self.labelMockupRawEEG.setGeometry(QtCore.QRect(0, 0, 520, 160))
		self.labelMockupRawEEG.setText("")
		self.labelMockupRawEEG.setPixmap(QtGui.QPixmap("../../../../.designer/backup/images/mockup-raw_eeg_waves.png"))
		self.labelMockupRawEEG.setObjectName("labelMockupRawEEG")
		self.verticalLayoutEEGPlot.addWidget(self.widgetPlotRawEEG)
		self.widgetPlotHistoryEmotivCognitiv = QtGui.QWidget(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widgetPlotHistoryEmotivCognitiv.sizePolicy().hasHeightForWidth())
		self.widgetPlotHistoryEmotivCognitiv.setSizePolicy(sizePolicy)
		self.widgetPlotHistoryEmotivCognitiv.setMinimumSize(QtCore.QSize(520, 160))
		self.widgetPlotHistoryEmotivCognitiv.setObjectName("widgetPlotHistoryEmotivCognitiv")
		self.labelMockupHistoryEmotivCognitiv = QtGui.QLabel(self.widgetPlotHistoryEmotivCognitiv)
		self.labelMockupHistoryEmotivCognitiv.setGeometry(QtCore.QRect(0, 0, 520, 160))
		self.labelMockupHistoryEmotivCognitiv.setText("")
		self.labelMockupHistoryEmotivCognitiv.setPixmap(QtGui.QPixmap("../../../../.designer/backup/images/mockup-esense_values_history.jpg"))
		self.labelMockupHistoryEmotivCognitiv.setScaledContents(True)
		self.labelMockupHistoryEmotivCognitiv.setObjectName("labelMockupHistoryEmotivCognitiv")
		self.verticalLayoutEEGPlot.addWidget(self.widgetPlotHistoryEmotivCognitiv)
		self.horizontalLayoutChartBottom = QtGui.QHBoxLayout()
		self.horizontalLayoutChartBottom.setObjectName("horizontalLayoutChartBottom")
		spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutChartBottom.addItem(spacerItem4)
		self.labelChartBottom = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.labelChartBottom.setTextFormat(QtCore.Qt.AutoText)
		self.labelChartBottom.setObjectName("labelChartBottom")
		self.horizontalLayoutChartBottom.addWidget(self.labelChartBottom)
		spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutChartBottom.addItem(spacerItem5)
		self.verticalLayoutEEGPlot.addLayout(self.horizontalLayoutChartBottom)
		self.widgetPlotHistoryThinkGear = QtGui.QWidget(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widgetPlotHistoryThinkGear.sizePolicy().hasHeightForWidth())
		self.widgetPlotHistoryThinkGear.setSizePolicy(sizePolicy)
		self.widgetPlotHistoryThinkGear.setMinimumSize(QtCore.QSize(520, 160))
		self.widgetPlotHistoryThinkGear.setObjectName("widgetPlotHistoryThinkGear")
		self.labelMockupHistoryThinkGear = QtGui.QLabel(self.widgetPlotHistoryThinkGear)
		self.labelMockupHistoryThinkGear.setGeometry(QtCore.QRect(0, 0, 520, 160))
		self.labelMockupHistoryThinkGear.setText("")
		self.labelMockupHistoryThinkGear.setPixmap(QtGui.QPixmap("../../../../.designer/backup/images/mockup-esense_values_history.jpg"))
		self.labelMockupHistoryThinkGear.setScaledContents(True)
		self.labelMockupHistoryThinkGear.setObjectName("labelMockupHistoryThinkGear")
		self.verticalLayoutEEGPlot.addWidget(self.widgetPlotHistoryThinkGear)
		self.widgetPlotHistoryEmotivAffectiv = QtGui.QWidget(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widgetPlotHistoryEmotivAffectiv.sizePolicy().hasHeightForWidth())
		self.widgetPlotHistoryEmotivAffectiv.setSizePolicy(sizePolicy)
		self.widgetPlotHistoryEmotivAffectiv.setMinimumSize(QtCore.QSize(520, 160))
		self.widgetPlotHistoryEmotivAffectiv.setObjectName("widgetPlotHistoryEmotivAffectiv")
		self.labelMockupHistoryEmotivAffectiv = QtGui.QLabel(self.widgetPlotHistoryEmotivAffectiv)
		self.labelMockupHistoryEmotivAffectiv.setGeometry(QtCore.QRect(0, 0, 520, 160))
		self.labelMockupHistoryEmotivAffectiv.setText("")
		self.labelMockupHistoryEmotivAffectiv.setPixmap(QtGui.QPixmap("../../../../.designer/backup/images/mockup-esense_values_history.jpg"))
		self.labelMockupHistoryEmotivAffectiv.setScaledContents(True)
		self.labelMockupHistoryEmotivAffectiv.setObjectName("labelMockupHistoryEmotivAffectiv")
		self.verticalLayoutEEGPlot.addWidget(self.widgetPlotHistoryEmotivAffectiv)
		spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutEEGPlot.addItem(spacerItem6)
		self.horizontalLayout_7.addLayout(self.verticalLayoutEEGPlot)
		self.verticalLayoutSessionProfile = QtGui.QVBoxLayout()
		self.verticalLayoutSessionProfile.setObjectName("verticalLayoutSessionProfile")
		self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.label.setObjectName("label")
		self.verticalLayoutSessionProfile.addWidget(self.label)
		self.horizontalLayout_4 = QtGui.QHBoxLayout()
		self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.textLabelControlConcentration = QtGui.QLabel(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelControlConcentration.sizePolicy().hasHeightForWidth())
		self.textLabelControlConcentration.setSizePolicy(sizePolicy)
		self.textLabelControlConcentration.setWordWrap(False)
		self.textLabelControlConcentration.setObjectName("textLabelControlConcentration")
		self.horizontalLayout_4.addWidget(self.textLabelControlConcentration)
		spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem7)
		self.pushButtonControlConcentrationEnable = QtGui.QPushButton(self.verticalLayoutWidget_2)
		self.pushButtonControlConcentrationEnable.setEnabled(False)
		self.pushButtonControlConcentrationEnable.setCheckable(True)
		self.pushButtonControlConcentrationEnable.setChecked(True)
		self.pushButtonControlConcentrationEnable.setObjectName("pushButtonControlConcentrationEnable")
		self.horizontalLayout_4.addWidget(self.pushButtonControlConcentrationEnable)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_4)
		self.progressBarControlConcentration = QtGui.QProgressBar(self.verticalLayoutWidget_2)
		self.progressBarControlConcentration.setEnabled(True)
		self.progressBarControlConcentration.setMinimumSize(QtCore.QSize(0, 60))
		self.progressBarControlConcentration.setProperty("value", 0)
		self.progressBarControlConcentration.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarControlConcentration.setObjectName("progressBarControlConcentration")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarControlConcentration)
		self.horizontalLayout_5 = QtGui.QHBoxLayout()
		self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.textLabelControlRelaxation = QtGui.QLabel(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelControlRelaxation.sizePolicy().hasHeightForWidth())
		self.textLabelControlRelaxation.setSizePolicy(sizePolicy)
		self.textLabelControlRelaxation.setWordWrap(False)
		self.textLabelControlRelaxation.setObjectName("textLabelControlRelaxation")
		self.horizontalLayout_5.addWidget(self.textLabelControlRelaxation)
		spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem8)
		self.pushButtonControlRelaxationEnable = QtGui.QPushButton(self.verticalLayoutWidget_2)
		self.pushButtonControlRelaxationEnable.setEnabled(False)
		self.pushButtonControlRelaxationEnable.setCheckable(True)
		self.pushButtonControlRelaxationEnable.setChecked(True)
		self.pushButtonControlRelaxationEnable.setObjectName("pushButtonControlRelaxationEnable")
		self.horizontalLayout_5.addWidget(self.pushButtonControlRelaxationEnable)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_5)
		self.progressBarControlRelaxation = QtGui.QProgressBar(self.verticalLayoutWidget_2)
		self.progressBarControlRelaxation.setEnabled(True)
		self.progressBarControlRelaxation.setMinimumSize(QtCore.QSize(0, 60))
		self.progressBarControlRelaxation.setProperty("value", 0)
		self.progressBarControlRelaxation.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarControlRelaxation.setObjectName("progressBarControlRelaxation")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarControlRelaxation)
		spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.verticalLayoutSessionProfile.addItem(spacerItem9)
		self.horizontalLayout_6 = QtGui.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.textLabelControlConnectionLevel = QtGui.QLabel(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelControlConnectionLevel.sizePolicy().hasHeightForWidth())
		self.textLabelControlConnectionLevel.setSizePolicy(sizePolicy)
		self.textLabelControlConnectionLevel.setWordWrap(False)
		self.textLabelControlConnectionLevel.setObjectName("textLabelControlConnectionLevel")
		self.horizontalLayout_6.addWidget(self.textLabelControlConnectionLevel)
		spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_6.addItem(spacerItem10)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_6)
		self.progressBarControlConnectionLevel = QtGui.QProgressBar(self.verticalLayoutWidget_2)
		self.progressBarControlConnectionLevel.setEnabled(True)
		self.progressBarControlConnectionLevel.setProperty("value", 0)
		self.progressBarControlConnectionLevel.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarControlConnectionLevel.setObjectName("progressBarControlConnectionLevel")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarControlConnectionLevel)
		self.line_6 = QtGui.QFrame(self.verticalLayoutWidget_2)
		self.line_6.setFrameShape(QtGui.QFrame.HLine)
		self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
		self.line_6.setObjectName("line_6")
		self.verticalLayoutSessionProfile.addWidget(self.line_6)
		self.formLayoutSessionData = QtGui.QFormLayout()
		self.formLayoutSessionData.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
		self.formLayoutSessionData.setObjectName("formLayoutSessionData")
		self.textLabelSessionTimeTitle = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.textLabelSessionTimeTitle.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelSessionTimeTitle.setObjectName("textLabelSessionTimeTitle")
		self.formLayoutSessionData.setWidget(0, QtGui.QFormLayout.LabelRole, self.textLabelSessionTimeTitle)
		self.textLabelSessionTime = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.textLabelSessionTime.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelSessionTime.setObjectName("textLabelSessionTime")
		self.formLayoutSessionData.setWidget(0, QtGui.QFormLayout.FieldRole, self.textLabelSessionTime)
		self.textLabelPacketsReceivedTitle = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.textLabelPacketsReceivedTitle.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelPacketsReceivedTitle.setObjectName("textLabelPacketsReceivedTitle")
		self.formLayoutSessionData.setWidget(1, QtGui.QFormLayout.LabelRole, self.textLabelPacketsReceivedTitle)
		self.textLabelPacketsReceived = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.textLabelPacketsReceived.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelPacketsReceived.setObjectName("textLabelPacketsReceived")
		self.formLayoutSessionData.setWidget(1, QtGui.QFormLayout.FieldRole, self.textLabelPacketsReceived)
		self.textLabelPacketsDroppedTitle = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.textLabelPacketsDroppedTitle.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelPacketsDroppedTitle.setObjectName("textLabelPacketsDroppedTitle")
		self.formLayoutSessionData.setWidget(2, QtGui.QFormLayout.LabelRole, self.textLabelPacketsDroppedTitle)
		self.textLabelPacketsDropped = QtGui.QLabel(self.verticalLayoutWidget_2)
		self.textLabelPacketsDropped.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelPacketsDropped.setObjectName("textLabelPacketsDropped")
		self.formLayoutSessionData.setWidget(2, QtGui.QFormLayout.FieldRole, self.textLabelPacketsDropped)
		self.verticalLayoutSessionProfile.addLayout(self.formLayoutSessionData)
		spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutSessionProfile.addItem(spacerItem11)
		self.horizontalLayout_7.addLayout(self.verticalLayoutSessionProfile)
		spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_7.addItem(spacerItem12)
		self.verticalLayout.addLayout(self.horizontalLayout_7)
		self.webViewEEG = QtWebKit.QWebView(self.verticalLayoutWidget_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.webViewEEG.sizePolicy().hasHeightForWidth())
		self.webViewEEG.setSizePolicy(sizePolicy)
		self.webViewEEG.setObjectName("webViewEEG")
		self.verticalLayout.addWidget(self.webViewEEG)
		spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayout.addItem(spacerItem13)

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		Form.setWindowTitle(QtGui.QApplication.translate("Form", "Puzzlebox Jigsaw - Plug-in - EEG", None, QtGui.QApplication.UnicodeUTF8))
		self.labelEEGHeadsetModel.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">EEG Headset Model</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGHeadsetModel.setItemText(0, QtGui.QApplication.translate("Form", "NeuroSky MindWave Mobile", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGHeadsetModel.setItemText(1, QtGui.QApplication.translate("Form", "NeuroSky MindWave", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGHeadsetModel.setItemText(2, QtGui.QApplication.translate("Form", "NeuroSky MindSet", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGHeadsetModel.setItemText(3, QtGui.QApplication.translate("Form", "Emotiv EPOC", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGHeadsetModel.setItemText(4, QtGui.QApplication.translate("Form", "InterAxon Muse", None, QtGui.QApplication.UnicodeUTF8))
		self.labelEEGServerSource.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">EEG Data Source</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGSource.setItemText(0, QtGui.QApplication.translate("Form", "Hardware Device", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGSource.setItemText(1, QtGui.QApplication.translate("Form", "ThinkGear Emulator", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGSource.setItemText(2, QtGui.QApplication.translate("Form", "Puzzlebox Synapse", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGSource.setItemText(3, QtGui.QApplication.translate("Form", "ThinkGear Connect", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGSource.setItemText(4, QtGui.QApplication.translate("Form", "BCI2000", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGSource.setItemText(5, QtGui.QApplication.translate("Form", "MuseIO", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxEEGSource.setItemText(6, QtGui.QApplication.translate("Form", "Spacebrew", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxDeviceSelect.setItemText(0, QtGui.QApplication.translate("Form", "No Devices Found", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonControlSearch.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))
		self.checkBoxControlEmulateThinkGear.setText(QtGui.QApplication.translate("Form", "Emulate NeuroSky ThinkGear", None, QtGui.QApplication.UnicodeUTF8))
		self.checkBoxControlEnableServer.setText(QtGui.QApplication.translate("Form", "Enable Synapse Server", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelSynapseHost.setText(QtGui.QApplication.translate("Form", "Host", None, QtGui.QApplication.UnicodeUTF8))
		self.lineEditSynapseHost.setText(QtGui.QApplication.translate("Form", "N/A", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelSynapsePort.setText(QtGui.QApplication.translate("Form", "<p align=\"center\">Port</p>", None, QtGui.QApplication.UnicodeUTF8))
		self.lineEditSynapsePort.setText(QtGui.QApplication.translate("Form", "N/A", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonSynapseServer.setText(QtGui.QApplication.translate("Form", "Connect", None, QtGui.QApplication.UnicodeUTF8))
		self.labelChartTop.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Raw EEG Waves</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelChartBottom.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Brain Signals History</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.label.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Current Data</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelControlConcentration.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Concentration</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonControlConcentrationEnable.setToolTip(QtGui.QApplication.translate("Form", "enable/disable concentration processing", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonControlConcentrationEnable.setText(QtGui.QApplication.translate("Form", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelControlRelaxation.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Relaxation</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonControlRelaxationEnable.setToolTip(QtGui.QApplication.translate("Form", "enable/disable relaxation processing", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonControlRelaxationEnable.setText(QtGui.QApplication.translate("Form", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelControlConnectionLevel.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Connection Level</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelSessionTimeTitle.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Connection Time</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelSessionTime.setText(QtGui.QApplication.translate("Form", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelPacketsReceivedTitle.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Packets Received</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelPacketsReceived.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelPacketsDroppedTitle.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Packets Dropped</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelPacketsDropped.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
